name: dl
description: Simply library to download files.
version: 1.0.0
homepage: https://github.com/zyrouge/dart_dl

environment:
    sdk: ">=2.17.0-87.0.dev <3.0.0"

dev_dependencies:
    test: ^1.16.0
    very_good_analysis: ^2.4.0
