name: dl
description: Simple library to download files easily.
version: 1.0.5
homepage: https://github.com/zyrouge/dart_dl/blob/main/README.md

environment:
    sdk: ">=2.12.0 <3.0.0"

dependencies:

dev_dependencies:
    test: ^1.16.0
    zlint:
        git:
            url: git://github.com/zyrouge/dart_zlint.git
            ref: main
