name: dl
description: Simple library to download files easily.
version: 1.0.2
homepage: https://github.com/zyrouge/dart_dl/blob/main/README.md

environment:
    sdk: ">=2.12.0 <3.0.0"

dependencies:

dev_dependencies:
    test: ^1.16.0
    very_good_analysis: ^2.4.0
